name: Fortify Aviator
on:
  workflow_dispatch:  # Allows manual trigger with inputs
  push:
    branches:
      - 'dev/*'
env:
  AVIATOR_APP_NAME: "Petstore"

  SSC_APP_NAME: petstore
  SSC_APP_VER_NAME: "v2"

jobs:
  fortify-sast-aviator:
    name: Fortify SAST Aviator Audit
    runs-on: ubuntu-latest

    steps:
      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v2
        with:
          export-path: true
          fcli: latest
      - name: Use Jar based FCLI
        run: |
          # ${FCLI_CMD} tool fcli list-platforms
          ${FCLI_CMD} tool fcli install --platform java --base-dir "/home/$USER/work/_temp/fortify/tools"
          ls -laR /home/$USER/work/_temp/fortify/tools

      - name: Setup Aviator Prerequisites
        run: |
          printf "%s" "${{secrets.FORTIFY_AVIATOR_TOKEN}}" > aviator_token.json
          # ${FCLI_CMD} aviator session login --url "${{vars.FORTIFY_AVIATOR_URL}}" --token aviator_token.json
          # ${FCLI_CMD} ssc session login --token "${{ secrets.SSC_TOKEN }}" --url "${{ secrets.SSC_URL }}"
          fcli aviator session login --url "https://ams.aviator.fortify.com" --token aviator_token.json
          fcli ssc session login --token "${{ secrets.SSC_TOKEN }}" --url "${{ secrets.SSC_URL }}"

      - name: Upload fortifypackage.zip
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: aviator_token.json
          retention-days: 1

      - name: Aviator Audit
        run: |
          fcli aviator ssc audit --av "${{env.SSC_APP_NAME}}:${{env.SSC_APP_VER_NAME}}" --app "${{env.AVIATOR_APP_NAME}}" 

      - name: Cleanup
        if: ${{ always() }}
        run: |
          fcli ssc session logout || true
          fcli aviator session logout || true